repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-yaml
  - id: check-added-large-files
  - id: fix-encoding-pragma
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: ^notebooks/

- repo: https://github.com/kynan/nbstripout
  rev: 0.5.0
  hooks:
  - id: nbstripout

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
  - id: black-jupyter

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.6.4
  hooks:
    - id: isort
